### PR TITLE
fix: add WithMessageNotContaining assertion for exception messages

### LINKED ISSUE #3104: add WithMessageNotContaining() to ThrowsException<>()
The `WithMessageContaining()` extension is helpful. But sometimes, you actually want to make sure the exception message does not contain a certain phrase. 

I can add a PR if desired.

### PR DESCRIPTION
**Pull request by thomhurst**
Fixes #3104

### CODE REVIEW

File: TUnit.Assertions/Assertions/Throws/ThrowsException.cs [hunk 1]
```diff
@@ -50,6 +50,20 @@ public ThrowsException<TActual, TException> WithMessageContaining(string expecte
         return this;
     }
 
+    public ThrowsException<TActual, TException> WithMessageNotContaining(string expected, [CallerArgumentExpression(nameof(expected))] string? doNotPopulateThisValue = null)
```
Comment (vslee) [inline TUnit.Assertions/Assertions/Throws/ThrowsException.cs:53]: nit: perhaps the parameter should be named ```notExpected``` instead of ```expected```?
